name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mementomori11723/sentimental-analysis:latest
    - name: Push the image
      run: docker push mementomori11723/sentimental-analysis:latest
