name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t mementomori11723/sentimental-analysis:latest
    - name: Push the image
      run: |
        docker login -u mentomori11723 -p ${{ secrets.DEPLOY_KEY }}
        docker push mementomori11723/sentimental-analysis:latest
